Review
AndStrel/stellar-burgers pull request #2
Opened 2024-10-25 20:13 UTC by AndStrel

2024-10-25 21:12 UTC, SergeyK2004 requested changes
Очень хорошая работа. 
Тесты написаны аккуратно без лишнего кода. Код приятно читать. Тесты на Jest проходят без ошибок.

Но есть несколько замечаний, которые надо исправить:

* https://disk.yandex.ru/d/BG2zHT1GWF-mgg Тест cypres останавливается с ошибкой.
* Несколько замечаний к тестам в коде.

Исправьте указанные недочеты и присылайте работу на повторную проверку.

2024-10-25 21:12 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.intercept('GET', `**/api/ingredients`, {
Отлично:
Правильно, что используете intercept

2024-10-25 21:12 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.clearCookie('accessToken');
Отлично:
хорошо, что очищаете хранилище и куки после тестов.

2024-10-25 21:12 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.get(`.constructor-element__text`).contains(`Пробная булка №1`);
Надо исправить:
Обратите внимание, что вы не проверяете, что текст появился, вы проверяете, что он есть. Чтобы проверить, что он появился, нужно убедиться, что до нажатия кнопки его не было.

При проверке любого действия необходимо выполнить три шага:

1. Проверить, что элемент, который должен появиться в результате действия отсутствует.
2. Выполнить действие.
3. Проверить, что элемент появился в разметке.

Необходимо учесть это во всех проверках.

2024-10-25 21:12 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.get(`.J2V21wcp5ddf6wQCcqXv`).first().click();
Надо исправить:
Нельзя ориентироваться на названия классов, генерируемые системой. Используйте специальные дата-атрибуты для тестирования или выполняйте поиск элементов по более надежным селекторам явно прописанным в коде.

2024-10-25 21:12 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.get(`.xqsNTMuGR8DdWtMkOGiM`).should('exist');
Надо исправить:
По условию задания необходимо проверить, что модальное окно открывается (т.е. сначала было закрыто) и в открывшемся модальном окне отображается именно выбранный ингредиент.

2024-10-26 13:57 UTC, AndStrel commented
Постарался все поправить.
Спасибо за хорошие замечания!

2024-10-27 02:05 UTC, SergeyK2004 approved these changes
Отлично доработаны тесты. Сейчас логика тестирования поведения приложения полная и позволяет проверить все необходимые действия программы. 
Поздравляю со сдачей проекта. 
Желаю успехов в дальнейшем освоении профессии.

2024-10-27 02:05 UTC, SergeyK2004 commented on cypress/e2e/constructor.cy.ts
> +    cy.visit('http://localhost:4000');
**Можно лучше:**

http://localhost:4000 повторяется несколько раз в коде тестов. Нужно вынести в константу `testUrl`, чтобы можно было одним движением изменить урл для тестов
А можно в документации посмотреть, как настроить быстро `baseUrl` для cypress https://docs.cypress.io/api/commands/visit#Visit-is-automatically-prefixed-with-baseUrl

2024-10-27 02:05 UTC, SergeyK2004 commented on src/components/ui/burger-constructor/burger-constructor.tsx
> +    <ul className={styles.elements} data-cy='constructor-ingredient'>
Отлично:

Использование дата атрибутов для тестирования это хорошая практика.

2024-10-28 10:39 UTC, merged